# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gtt"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luiz Branco"]
  s.date = "2014-01-21"
  s.description = "Use your git commits to track how much time you spend coding."
  s.email = "me@luizbranco.com"
  s.executables = ["gtt"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/gtt.rb",
    "lib/gtt/cli.rb",
    "lib/gtt/commit.rb",
    "lib/gtt/config.rb",
    "lib/gtt/output.rb",
    "lib/gtt/talker.rb",
    "lib/gtt/tracker.rb"
  ]
  s.homepage = "http://github.com/luizbranco/gtt"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Git Time Tracker"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<rainbow>, [">= 1.1.4"])
      s.add_runtime_dependency(%q<json>, ["~> 1.7.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.9.0"])
      s.add_dependency(%q<rainbow>, [">= 1.1.4"])
      s.add_dependency(%q<json>, ["~> 1.7.7"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.9.0"])
    s.add_dependency(%q<rainbow>, [">= 1.1.4"])
    s.add_dependency(%q<json>, ["~> 1.7.7"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

